name: Coderrect CI Integration
description: >
  Scan your code with Coderrect to detect concurrency bugs,
  and upload the detection report to Coderrect remote server.
branding:
  icon: check
  color: green
inputs:
  buildCommand:
    description: "Custom build command"
    required: false
    default: "make -j"
  cleanCommand:
    description: "Custom clean command"
    required: false
    default: "make clean"
  buildPath:
    description: "The relative path for your build directory"
    required: false
    default: "."
  host:
    description: "Custom remote host for HTML report"
    required: false
    default: "DEFAULT"
  options:
    description: "Command line options for Coderrect Scanner"
    required: false
    default: "-analyzeAllBinaries"
  config:
    description: "Coderrect configuration file"
    required: false
    default: ""
runs:
  using: composite
  steps:
    - run: | 
        wget -q https://public-installer-pkg.s3.us-east-2.amazonaws.com/coderrect-linux-develop.tar.gz
        tar zxf coderrect-linux-develop.tar.gz
        echo "$PWD/coderrect-linux-develop/bin" >> $GITHUB_PATH
        cd ${{ inputs.buildPath }}
        ${{ inputs.cleanCommand }}
      shell: bash
    - run: |
        cd ${{ inputs.buildPath }}
        coderrect ${{ inputs.options }} ${{ inputs.buildCommand }}
      shell: bash
    - run: |
        cd ${{ inputs.buildPath }}
        coderrect -publishResults -report.host=${{ inputs.host }}
      shell: bash
